### ISSUE TITLE
Add iguides-common css/bankApp.css to the Bulkhead guide

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguide-bulkhead#126]
Add the bankApp.css to the Bulkhead guide so that changes can be easily seen across all fault tolerance example scenarios.

Bulkhead.css imports the ASAP font, contains the css for the eBank header, as well as for the step header (the second div on the pages that defines what the page is for).  We can remove these items from the Bulkhead guide files and instead import the common guides bankApp.css.

Note: may also have to update the sample app in the /finish directory to contain a copy of bankApp.css.

**Comment by wexantis** [comment]
I'm not sure what to do here. Bulkhead.css doesn't contain code also found in bankApp.css. However, chat.css does. Should I remove those duplicate items from chat.css?

**Comment by lavenal** [comment]
Denise, I don't think this is an issue anymore. Could you confirm?

**Comment by dmorgant** [comment]
This issue has been taken care of by the conversion to multipane design code.  Closing.
