### ISSUE TITLE
Update features: bulkhead

### ISSUE THREAD

**Issue by k8vance88** [OpenLiberty/iguide-bulkhead#179]
mpFaultTolerance needs to be updated to version 2.1.

There are two new variables that can be set on the @Fallback annotation.  They are applyOn and skipOn.   If the thrown exception matches or is a child of an exception in the appyOn array, then the fallback method will be invoked.  If the exception matches or is a child of an exception in the skipOn array, then the exception is rethrown.  If it is in both, the exception is rethrown.

The current iguide code specifies only the Fallback method.  We need to change this to also include the applyOn when BulkheadException is thrown.  I don't think the current scenario lends well to using the skipOn parameter.  If there is not a good example for using skipOn in this guide, I think we can simply mention it as another option if we cannot work it in the scenario adequately.

**Comment by dmorgant** [comment]
As per Michal in https://github.com/OpenLiberty/iguide-circuit-breaker/issues/288, the bulkhead guide will not include information on the `applyOn` and `skipOn` parameters for the @Fallback annotation directly.  Instead we will link to the Circuit Breaker guide where these parameters will be defined and used in the example.

The Circuit Breaker interactive guide was updated to define and show how to use the parameters (see OpenLiberty/iguide-circuit-breaker#292). The Bulkhead guide will be updated to call out `applyOn` and `skipOn` being covered in the CircuitBreaker guide.

For example, we will change

    "For more information on using the @Fallback annotation to identify a method, see the MicroProfile Circuit Breaker guide."

to something like

    "For more information on using the @Fallback annotation to identify a method or using the skipOn and failOn parameters, see the MicroProfile Circuit Breaker guide."

Fallback:
https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.1/microprofile-fault-tolerance-spec.html#_specify_the_criteria_for_triggering_fallback

This update was requested as part of OpenLiberty/iguide-circuit-breaker#288.

**Comment by dmorgant** [comment]
Since the new parameters for the @Fallback annotation, `applyOn` and `skipOn`, are new as of mpFaultTolerance-2.1, the bulkhead guide will also have its versions updated throughout.

Currently, io.openliberty openliberty-runtime 20.0.0.12 is the latest runtime on maven.  This includes mpFaultTolerance-2.1 (but not 3.0).
